# Generated by Django 3.2.5 on 2021-08-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='subscribers',
        ),
    ]
