# Generated by Django 3.2.5 on 2021-08-04 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0002_remove_channel_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='user_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
