# Generated by Django 3.2.5 on 2021-07-29 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0002_auto_20210728_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='user',
        ),
    ]
