# Generated by Django 3.2.5 on 2021-08-04 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0003_auto_20210804_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='user_id',
            new_name='user',
        ),
    ]
