# Generated by Django 3.2.5 on 2021-07-30 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0004_video_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='user',
            new_name='user_id',
        ),
    ]
